export const Team_Data_EN = [
    {
        name: "Liana Maria Taborda Lima",
        role: "Senior Lawyer",
        slug: "liana-taborda-lima",
        memberPage: "/sobre/liana-taborda-lima",
        linkedin: "https://www.linkedin.com/in/liana-taborda-lima-7b1b1b1b1/",
        oab: "OAB/PR 18983",
        oabLink: "https://www.oabpr.org.br/servicos-consulta-de-advogados/consulta-de-advogado/?oabn=18983&tpinsc=A",
        bio: [
            "An experienced lawyer and founding partner of the firm Taborda Lima & Advogados Associados, based in Curitiba. With over twenty years of experience in the legal market, Liana stands out in the international field, focusing on International Trade, Customs Law, and U.S. Immigration Law.",
            "In addition to holding a Masters degree in International Law from the Pontifical Catholic University of Paraná, Liana also earned a Masters in Business Law and Citizenship from the Centro Universitário Curitiba in 2015.",
            "Active in the international area, Liana has expertise in International Trade, Customs Law, and Immigration Law for the U.S., Europe, and various other countries.",
            "With her solid academic background and extensive practical experience, Liana is a respected reference in the legal field, providing reliable and strategic legal guidance to her clients.",
        ],
        image: "/team/equipe_placeholder.png",
    },
    {
        name: "Cesar Augusto Taborda Lima",
        role: "Partner Lawyer",
        slug: "cesar-augusto-taborda-lima",
        memberPage: "/sobre/cesar-augusto-taborda-lima",
        linkedin: "https://www.linkedin.com/in/cesar-augusto-taborda-lima-7b1b1b1b1/",
        oab: "OAB/PR 112654",
        oabLink: "https://www.oabpr.org.br/servicos-consulta-de-advogados/consulta-de-advogado/?oabn=112654&tpinsc=A",
        bio: [
            "Cesar Augusto Taborda Lima is a partner at the firm Taborda Lima and serves as the Head of Immigration and International Law at Taborda Lima & Advogados Associados.",
            "With expertise in the areas of Immigration and Migration and International Law, his services include legal consultancy, intellectual property law, entertainment law, immigration law, and corporate law.",
            "Having a full-time career at Taborda Lima & Advogados Associados since January 2017, accumulating over 7 years and 2 months of experience, Cesar has an academic background in Law and a postgraduate degree in International Law from the Pontifical Catholic University of Paraná.",
        ],
        image: "/team/equipe_cesar_2025.png",
    },
    {
        name: "Rafael Weiss Brandt",
        role: "Controllership",
        slug: "rafael-weiss-brandt",
        memberPage: "/sobre/rafael-weiss-brandt",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_rafael_2025.png",
    },
    {
        name: "Daniella da Matta",
        role: "Controllership",
        slug: "daniella-da-matta",
        memberPage: "/sobre/daniella-da-matta",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_placeholder.png",
    },
    {
        name: "Susan Petza",
        role: "Controllership",
        slug: "susan-petza",
        memberPage: "/sobre/susan-petza",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_susan_2025.png",
    },
    {
        name: "Amanda",
        role: "Controllership",
        slug: "amanda",
        memberPage: "/sobre/amanda",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_placeholder.png",
    },
    {
        name: "Juliana Da Costa Prataviera",
        role: "Compliance Department",
        slug: "juliana-pratavieira",
        memberPage: "/sobre/juliana-pratavieira",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_juliana_2025.png",
    },
    {
        name: "Luana Moratelli Orofino",
        role: "Legal Department",
        slug: "luana-moratelli",
        memberPage: "/sobre/luana-moratelli",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_luana_2025.png",
    },
    {
        name: "Carlos Miguel Perotti",
        role: "Sports Law Department",
        slug: "carlos-miguel-perotti",
        memberPage: "/sobre/carlos-miguel-perotti",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_carlos_2025.png",
    },
    {
        name: "Gabriela Magagnin Stark",
        role: "Legal Department",
        slug: "gabriela-stark",
        memberPage: "/sobre/gabriela-stark",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_gabriela_2025.png",
    },
    {
        name: "Giovanna Moreira de Souza Carrão",
        role: "Admnistrative Department",
        slug: "giovana-moreira-de-souza-carrao",
        memberPage: "/sobre/giovana-moreira-de-souza-carrao",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_giovana_2025.png",
    },
    {
        name: "Ester Oliveira Marques",
        role: "Legal Department",
        slug: "ester-oliveira-marques",
        memberPage: "/sobre/ester-oliveira-marques",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_ester_2025.png",
    },
    {
        name: "Sofia Paula Leandro",
        role: "Marketing Department",
        slug: "sofia-paula-leandro",
        memberPage: "/sobre/sofia-paula-leandro",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_sofia_2025.png",
    },
];
