export const Team_Data_PT = [
    {
        name: "Liana Maria Taborda Lima",
        role: "Advogada Senior",
        slug: "liana-taborda-lima",
        memberPage: "/sobre/liana-taborda-lima",
        linkedin: "https://www.linkedin.com/in/liana-taborda-lima-7b1b1b1b1/",
        oab: "OAB/PR 18983",
        oabLink: "https://www.oabpr.org.br/servicos-consulta-de-advogados/consulta-de-advogado/?oabn=18983&tpinsc=A",
        bio: [
            "Advogada experiente e sócia fundadora do escritório Taborda Lima & Advogados Associados, sediado em Curitiba. Com mais de vinte anos de atuação no mercado jurídico, Liana se destaca na área internacional, concentrando-se em Comércio Internacional, Direito Aduaneiro e Imigratório dos EUA.",
            "Além de possuir um mestrado em Direito Internacional pela Pontifícia Universidade Católica do Paraná, Liana também é mestra em Direito Empresarial e Cidadania pelo Centro Universitário Curitiba, em 2015.",
            "Atuante na área internacional, Liana tem expertise em Comércio Internacional, Direito Aduaneiro e Imigratório para os EUA, Europa e diversos outros países.",
            "Com sua sólida formação acadêmica e vasta experiência prática, Liana é uma referência respeitada no meio jurídico, proporcionando orientação jurídica confiável e estratégica para seus clientes.",
        ],
        image: "/team/equipe_liana_2025.png",
    },
    {
        name: "Cesar Augusto Taborda Lima",
        role: "Advogado Sócio",
        slug: "cesar-augusto-taborda-lima",
        memberPage: "/sobre/cesar-augusto-taborda-lima",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 112654",
        oabLink: "https://www.oabpr.org.br/servicos-consulta-de-advogados/consulta-de-advogado/?oabn=112654&tpinsc=A",
        bio: [
            "Cesar Augusto Taborda Lima é sócio do escritório Taborda Lima, e atua como Head of Immigration and International Law na Taborda Lima & Advogados Associados.",
            "Com expertise nas áreas de Imigração/Migração e Direito Internacional, Seus serviços incluem consultoria jurídica, direito de propriedade intelectual, direito do entretenimento, direito imigratório e direito societário.",
            "Com uma carreira de tempo integral na Taborda Lima & Advogados Associados desde janeiro de 2017, acumulando mais de 7 anos e 2 meses de experiência, Cesar possui formação acadêmica em Direito e uma pós graduação em Direito Internacional pela Pontifícia Universidade Católica do Paraná.",
        ],
        image: "/team/equipe_cesar_2025.png",
    },
    {
        name: "Rafael Weiss Brandt",
        role: "Controladoria",
        slug: "rafael-weiss-brandt",
        memberPage: "/sobre/rafael-weiss-brandt",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_rafael_2025.png",
    },
    {
        name: "Daniella da Matta",
        role: "Controladoria",
        slug: "daniella-da-matta",
        memberPage: "/sobre/daniella-da-matta",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_daniela_2025_B.png",
    },
    {
        name: "Susan Petza",
        role: "Controladoria",
        slug: "susan-petza",
        memberPage: "/sobre/susan-petza",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_susan_2025.png",
    },
    {
        name: "Amanda",
        role: "Controladoria",
        slug: "amanda",
        memberPage: "/sobre/amanda",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],
        image: "/team/equipe_placeholder.png",
    },
    {
        name: "Juliana Da Costa Prataviera",
        role: "Departamento de Compliance",
        slug: "juliana-pratavieira",
        memberPage: "/sobre/juliana-pratavieira",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: [
            "Graduada em Direito pela Faculdade de Cuiabá - Unic",
            "Pós-Graduada em Processo Civil  na FACUMINAS",
            "Pós-Graduanda em Compliance e Gestão de Risco na Faculdade Anhanguera",
            "Idiomas: Português, Inglês e Espanhol",
        ],

        image: "/team/equipe_juliana_2025.png",
    },
    {
        name: "Luana Moratelli Orofino",
        role: "Departamento Jurídico",
        slug: "luana-moratelli",
        memberPage: "/sobre/luana-moratelli",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: [
            "Graduada em Direito pela Universidade Federal do Paraná - UFPR",
            "Pós-Graduanda em Direito Internacional na Universidade Cruzeiro do Sul",
            "Certificado sobre  Tribunal Penal Internacional - Harvard Model Congress Latin America 2015",
            "Idiomas: Português ,Inglês, Francês e Alemão",
        ],

        image: "/team/equipe_luana_2025.png",
    },
    {
        name: "Carlos Miguel Perotti",
        role: "Departamento de Direito Desportivo",
        slug: "carlos-miguel-perotti",
        memberPage: "/sobre/carlos-miguel-perotti",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["Graduando em Direito pela Universidade Federal do Paraná -UFPR", "Idiomas: Português, Inglês, Espanhol e Italiano"],

        image: "/team/equipe_carlos_2025.png",
    },
    {
        name: "Gabriela Magagnin Stark",
        role: "Departamento Jurídico",
        slug: "gabriela-stark",
        memberPage: "/sobre/gabriela-stark",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_gabriela_2025.png",
    },
    {
        name: "Giovanna Moreira de Souza Carrão",
        role: "Departamento Administrativo",
        slug: "giovana-moreira-de-souza-carrao",
        memberPage: "/sobre/giovana-moreira-de-souza-carrao",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["Graduanda em Administração pela Universidade Federal do Paraná -UFPR", "Idiomas:  Português e Inglês"],

        image: "/team/equipe_giovana_2025.png",
    },
    {
        name: "Ester Oliveira Marques",
        role: "Departamento Jurídico",
        slug: "ester-oliveira-marques",
        memberPage: "/sobre/ester-oliveira-marques",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["Graduanda em Direito pela Faculdade de Administração e Economia - FAE", "Idiomas: Português, Inglês,  Espanhol  e Alemão"],

        image: "/team/equipe_ester_2025.png",
    },
    {
        name: "Sofia Paula Leandro",
        role: "Departamento de Marketing",
        slug: "sofia-paula-leandro",
        memberPage: "/sobre/sofia-paula-leandro",
        linkedin: "https://www.linkedin.com/",
        oab: "OAB/PR 123456",
        oabLink: "https://www.oabpr.org.br/",
        bio: ["", "", ""],

        image: "/team/equipe_sofia_2025.png",
    },
];
